<a href="https://colab.research.google.com/github/cdy9777/GitriniForkRepo/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. pytorch Fundamentals

resource link : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
print(torch.__version__)

2.1.0+cu118


In [ ]:
## intro to Tensors

### creating tensor
scalar = torch.tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector.ndim # numbeor of braket
vector.shape # number of pairs

torch.Size([2])

In [ ]:
# Matrix matrix and tensor는 대문자 표기
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX.ndim # 2차원
MATRIX.shape # 2*2

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR.ndim # 3차원
TENSOR.shape # 1*3*3 #1 <- 가장 바깥 브래킷 안의 요소 수, 3 <- 두번 째 바깥 3 <- 가장 내부 브래킷 요소 수)

torch.Size([1, 3, 3])

### Random tensors
why random tensors
-> random tensors are important because the way many neural networks learn is that start with tensors full of random numbers and then adjust those random numbers to better represent the data


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4) # torch.rand(size=(3,3))과 같은 결과
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_tensor_image = torch.rand(size = (224,224,3)) # height, width, color_channel
random_tensor_image.shape, random_tensor_image.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(size=(3,4)) # default data type is torch.float32
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4)) # default data type is torch.float32
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_thousand = torch.arange(start = 1, end = 11, step = 1)
one_to_thousand

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_thousand) # same shape of input
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype
**Note:** Tensor data-type is one of the 3 big errors you'll run into with Pytorch & Deep learning

1. tensors not right data-type
2. tensors not right shape
3. tensors not on the right device

In [ ]:
# float32 tensor <- default data type
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None) # dtype(what data type is), device(What device is your tensor on), requires_grad(whether or not to track gradients with tensors operations)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
int_32 = torch.tensor([3,6,9],dtype= torch.int32)
int_32

tensor([3, 6, 9], dtype=torch.int32)

### getting information from tensors(tensor's attribute)
1. tensor.dtype
2. tensor.shape
3. tensor.device

### Manipulating Tensors(tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication(행렬곱)

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 100 # add 100 to all element
tensor_mul = tensor * 10 # multiply 10 to all element
tensor_min = tensor - 10 # subtract 10 to all element

tensor([101, 102, 103])

In [ ]:
# in-bulit fuction
torch.mul(tensor, 10)
torch.add(tensor, 10)

### Matrix multiplication

Two main ways of performing multiplications in neural networks and deep learning :

1. Element-wise Multiplication
2. Matrix multiplication

In [ ]:
# element-wise multiplication
print(tensor*tensor)

# 행렬곱
print(torch.matmul(tensor,tensor))
print(tensor @ tensor) # 같은 표현 torch.mm() 역시 행렬곱 표현

tensor([1, 4, 9])
tensor(14)
tensor(14)


In [ ]:
tensor_a = torch.tensor([[1,2],[3,4],[5,6]])
# print(tensor_a.shape)
tensor_b = torch.tensor([[7,10],[8,11],[9,12]])

print(torch.mm(tensor_a, tensor_b.T))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [ ]:
## tensor min, max, mean (tensor aggregation)
tensor = torch.arange(0,100,10)
print(tensor)

print(tensor)
print(tensor.min()) # torch.min(tensor)
print(tensor.max()) # torch.max(tensor)
print(torch.mean(tensor.type(torch.float32))) # torch.mean(tensor)
print(tensor.sum()) # torch.sum(tensor)



tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(90)
tensor(45.)


In [ ]:
## Find the positional min and max
print(tensor.argmin())
print(tensor.argmax()) # return index value

tensor(0)
tensor(9)


## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking(hstack, vstack) - combine multiple tensors
* Squeeze(unsqueeze) - reemove all '1' dimensions from a tensor(unsqueeze add '1' dimension to a target tensor)
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
x = torch.arange(1.,10.)
x_reshaped = x.reshape(1,9)
print(x_reshaped, x_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [ ]:
# Change the view(Change z changes x (share same memory))
z = x.view(1,9)
z[:,0] =5
print(z,x)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1) # dim 0 은 4*9 dim 1 = 9*4
print(x_stacked)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [ ]:
# Squeeze(unsqueeze)
# torch.squeeze() - removes all single dimensions from a target sensor
print(x_reshaped.shape)
# x_reshaped.squeeze()
print(x_reshaped.squeeze(), x_reshaped.squeeze().shape) # '1'인 차원을 모두 제거

x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim = 0) # dim에 따라 다른 결과
print(x_unsqueezed)

torch.Size([1, 9])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor -> Permute도 view 관점 같은 메모리 속 데이터를 공유하기 때문에 두 변수 중 값이 변하며 따라 변함.
x_origin = torch.rand(size=(224,224,3)) # h * w * channel
x_permuted = x_origin.permute(2,0,1) # 3 * 224(h) * 224(w) shift axis

## parameter dim을 아직 명확하게 이해하짐 못함.

## Indexing(selecting data from tensors)
similar to indexing with Numpy

In [3]:
tensor = torch.arange(1,10)
x = tensor.reshape(1,3,3)
print(x)

print(x[0][1][2]) # 2 -> 1 -> 0 차원 element를 return


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(6)


In [14]:
# indexing 법칙 아직 이해 못함.
print(x[:,1])
print(x[:, :, 2]) # 첫번째 2차원 matrix의 3번째 열을 가져와.
print(x[0,1,1]) # 3차원의 처음 원소의 2번째 행 2번쟤 열의 값을 가져와

new = torch.arange(1,9).reshape(2,4)
print(new)
print(new[:,1]) # 2번째 열을 가져와

tensor([[4, 5, 6]])
tensor([[3, 6, 9]])
tensor(5)
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([2, 6])


In [17]:
x[:,2,2]

tensor([9])

## Pytorch tensors & Numpy
Numpy is a popular scientific python numerical computing library.

Pytorch has functionality to interact with it.

* Data in Numpy -> Pytorch tensor (torch.from_numpy(ndarray)
* Pytorch tensor -> Numpy(torch.Tensor.numpy()))

In [22]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array,array.dtype, tensor) # tensor의 기본 데이터타입은 float32이지만, 메소드로 numpy 배열을 받으면 float64 data type)
print(tensor.type(torch.float32))


tensor = torch.ones(7)
print(tensor)
np_array = torch.Tensor.numpy(tensor)
print(np_array) # data type tensor의 default인 float32 유지

# They don't share memory

[1. 2. 3. 4. 5. 6. 7.] float64 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]


## Reproducibility(trying to take random out of random)

To reduce the randomness in neural networks and Pytorch comes the concept of a **randon seed**.
Essentially what the random seed does is 'flavour' the randomness.

In [23]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_1 = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_2 = torch.rand(3,4)

print(random_tensor_1 == random_tensor_2)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs(and making faster computations)

How can we use GPUs?
* easiset way -> Google colab
* use my own GPUs -> takes a little bit of setup and requires the investment of purchasing a GPU
* use Cloud computing -> GCP, AWS, Azure(rent computers on the cloud and access them)

For 2,3 Pytorch+GPU drivers(CUDA) takes a little bit of setting up, refer to Pytorch setup documentation.

In [24]:
!nvidia-smi

Tue Oct 24 02:47:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [26]:
# check for GPU Access with Pytorch
torch.cuda.is_available() # get access to GPU

# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'

## Putting tensors(and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster compuations.

In [28]:
# move tensor to GPU(if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# if tensor is on GPU, can't transform it to Numpy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

[1. 1. 1. 1. 1. 1. 1.]
